openapi: 3.2.0
info:
  title: Layup endpoints Bank Transaction Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: BankTransactionService
paths:
  /v1/bank-transactions:
    post:
      operationId: BankTransactionService_create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelBankTransactionResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - BankTransactionService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelBankTransactionCreateRequest'
        required: true
      summary: Bank transaction service create
      x-summary-source: derived
  /v1/bank-transactions/link-batch:
    put:
      operationId: BankTransactionService_linkBatch
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelBankTransactionResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: ids
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: bankTransactionBatchId
        in: query
        required: true
        schema:
          type: string
      tags:
      - BankTransactionService
      summary: Bank transaction service link batch
      x-summary-source: derived
  /v1/bank-transactions/{id}/payment:
    post:
      operationId: BankTransactionService_createPayment
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelBankTransactionResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - BankTransactionService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelBankTransactionPaymentRequest'
        required: true
      summary: Bank transaction service create payment
      x-summary-source: derived
  /v1/release-suspense:
    put:
      operationId: BankTransactionService_update
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelBankTransactionResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - BankTransactionService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelBankTransactionUpdate'
        required: true
      summary: Bank transaction service update
      x-summary-source: derived
components:
  schemas:
    modelBankTransactionCreateRequest:
      type: object
      properties:
        bankTransactions:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelBankTransactionCreate'
    modelBankTransactionCreate:
      type: object
      properties:
        date:
          type: string
        description:
          type: string
        reference:
          type: string
        amountInCents:
          type: integer
          format: int32
        balanceInCents:
          type: integer
          format: int32
        bank:
          type: string
        fileStorageReference:
          type: string
    modelBankTransactionResponse:
      type: object
    modelBankTransactionUpdate:
      type: object
      properties:
        bankTransactionIds:
          type: array
          items:
            type: string
    modelBankTransactionPaymentRequest:
      type: object
      properties:
        destinationId:
          type: string
        destinationType:
          type: string
        amount:
          type: integer
          format: int32
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
