openapi: 3.2.0
info:
  title: Layup endpoints Invoices Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: InvoicesService
paths:
  /v1/invoice/{id}:
    put:
      operationId: InvoicesService_updatePdf
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInvoiceResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - InvoicesService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelInvoiceUpdatePdfRequest'
        required: true
      summary: Invoices service update pdf
      x-summary-source: derived
  /v1/invoices:
    get:
      operationId: InvoicesService_getMany
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInvoiceGetManyResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: from
        in: query
        required: false
        schema:
          type: string
      - name: to
        in: query
        required: false
        schema:
          type: string
      - name: reference
        in: query
        required: false
        schema:
          type: string
      - name: status
        in: query
        required: false
        schema:
          type: string
      tags:
      - InvoicesService
      summary: Invoices service get many
      x-summary-source: derived
    post:
      operationId: InvoicesService_create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInvoicesResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - InvoicesService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelDateTimeRange'
        required: true
      summary: Invoices service create
      x-summary-source: derived
    put:
      operationId: InvoicesService_update
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInvoiceResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - InvoicesService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelInvoiceUpdateRequest'
        required: true
      summary: Invoices service update
      x-summary-source: derived
  /v1/invoices/:id/pdf:
    get:
      operationId: InvoicesService_getPdf
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInvoicePdfResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      tags:
      - InvoicesService
      summary: Invoices service get pdf
      x-summary-source: derived
  /v1/invoices/fees:
    post:
      operationId: InvoicesService_createByFees
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInvoicesResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - InvoicesService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelInvoiceFeesCreateRequest'
        required: true
      summary: Invoices service create by fees
      x-summary-source: derived
  /v1/invoices/{id}:
    get:
      operationId: InvoicesService_getInvoiceById
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInvoiceReport'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - InvoicesService
      summary: Invoices service get invoice by id
      x-summary-source: derived
  /v1/invoices/{id}/report:
    get:
      operationId: InvoicesService_getInvoiceReportById
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelGenerateReportResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - InvoicesService
      summary: Invoices service get invoice report by id
      x-summary-source: derived
components:
  schemas:
    modelInvoicesResponse:
      type: object
      properties:
        invoiceIds:
          type: array
          items:
            type: string
    modelInvoiceUpdatePdfRequest:
      type: object
      properties:
        accountingPdfLocation:
          type: string
    modelInvoice:
      type: object
      properties:
        _id:
          type: string
        merchantId:
          type: string
        exVatAmount:
          type: integer
          format: int32
        vatAmount:
          type: integer
          format: int32
        totalAmount:
          type: integer
          format: int32
        settled:
          type: boolean
        reconciled:
          type: boolean
        bankTransactionId:
          type: string
        reference:
          type: string
        accountingInvoiceId:
          type: string
        accountingInvoiceNumber:
          type: string
        status:
          type: string
        createdAt:
          type: string
        billingMethod:
          type: string
    modelInvoiceFeesCreateRequest:
      type: object
      properties:
        feeIds:
          type: array
          items:
            type: string
    modelInvoicePdfResponse:
      type: object
      properties:
        redirectUrl:
          type: string
    modelGenerateReportResponse:
      type: object
      properties:
        report:
          $ref: '#/components/schemas/modelInvoiceReport'
    modelInvoiceGetManyResponse:
      type: object
      properties:
        invoices:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelInvoice'
    modelInvoiceResponse:
      type: object
    modelInvoiceReport:
      type: object
      properties:
        id:
          type: string
        merchantId:
          type: string
        exVatAmount:
          type: integer
          format: int32
        vatAmount:
          type: integer
          format: int32
        totalAmount:
          type: integer
          format: int32
        settled:
          type: boolean
        reconciled:
          type: boolean
        bankTransactionId:
          type: string
        reference:
          type: string
        accountingInvoiceId:
          type: string
        accountingInvoiceNumber:
          type: string
        status:
          type: string
        createdAt:
          type: string
        feesPerProduct:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelFeesPerProduct'
        report:
          $ref: '#/components/schemas/modelReport'
        billingMethod:
          type: string
    modelInvoiceUpdateRequest:
      type: object
      properties:
        invoiceId:
          type: string
        accountingInvoiceId:
          type: string
        accountingInvoiceNumber:
          type: string
    modelProduct:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        displayName:
          type: string
        feeType:
          type: string
        method:
          type: string
        billingType:
          type: string
    modelReport:
      type: object
      properties:
        totalFeesAmount:
          type: integer
          format: int32
        totalFeesExtAmount:
          type: integer
          format: int32
        totalAmountVAT:
          type: integer
          format: int32
        feesPerProductExcludingVATTotal:
          type: integer
          format: int32
        feesPerProductVATTotal:
          type: integer
          format: int32
        feesPerProductTotal:
          type: integer
          format: int32
        fees:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelJournalFees'
    modelJournalFees:
      type: object
      properties:
        id:
          type: string
        productName:
          type: string
        amountExcludingVAT:
          type: number
          format: double
        amountVAT:
          type: number
          format: double
        amountTotal:
          type: number
          format: double
        merchantId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        settlementId:
          type: string
        paymentId:
          type: string
    modelFeesPerProduct:
      type: object
      properties:
        quantity:
          type: integer
          format: int32
        amountTotal:
          type: number
          format: double
        amountExcludingVAT:
          type: number
          format: double
        amountVAT:
          type: number
          format: double
        product:
          $ref: '#/components/schemas/modelProduct'
    modelDateTimeRange:
      type: object
      properties:
        fromDateTime:
          type: string
        toDateTime:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
