openapi: 3.2.0
info:
  title: Layup endpoints Debit Order Mandate Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: DebitOrderMandateService
paths:
  /v1/debit-order-mandates:
    post:
      operationId: DebitOrderMandateService_create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebitOrderMandateResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - DebitOrderMandateService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelDebitOrderMandateCreateRequest'
        required: true
      summary: Debit order mandate service create
      x-summary-source: derived
  /v1/merchants/{merchantId}/debit-order-mandates:
    get:
      operationId: DebitOrderMandateService_get
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebitOrderMandateResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: merchantId
        in: path
        required: true
        schema:
          type: string
      tags:
      - DebitOrderMandateService
      summary: Debit order mandate service get
      x-summary-source: derived
components:
  schemas:
    modelDebitOrderMandateCreateRequest:
      type: object
      properties:
        merchantId:
          type: string
        reference:
          type: string
        holderName:
          type: string
        holderSurname:
          type: string
        contact:
          type: string
        accountType:
          type: string
        accountNumber:
          type: string
        branchCode:
          type: string
        identificationType:
          type: string
        identificationNumber:
          type: string
    modelDebitOrderMandateResponse:
      type: object
      properties:
        mandateId:
          type: string
        merchantId:
          type: string
        reference:
          type: string
        holderName:
          type: string
        holderSurname:
          type: string
        contact:
          type: string
        accountType:
          type: string
        accountNumber:
          type: string
        branchCode:
          type: string
        identificationType:
          type: string
        identificationNumber:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
