openapi: 3.2.0
info:
  title: Layup endpoints Journal Fee Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: JournalFeeService
paths:
  /v1/journal-fees:
    post:
      operationId: JournalFeeService_Create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelJournalFeeResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      tags:
      - JournalFeeService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelJournalFeeResponse'
        required: true
      summary: Journal fee service create
      x-summary-source: derived
components:
  schemas:
    modelJournalFeeResponse:
      type: object
      properties:
        _id:
          type: string
        productName:
          type: string
        amountTotal:
          type: number
          format: double
        amountExcludingVAT:
          type: number
          format: double
        amountVAT:
          type: number
          format: double
        orderId:
          type: string
        paymentPlanId:
          type: string
        paymentId:
          type: string
        merchantId:
          type: string
        settled:
          type: boolean
        reconciled:
          type: boolean
        settlementId:
          type: string
        invoiceId:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
