openapi: 3.2.0
info:
  title: Layup endpoints Pay At Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: PayAtService
paths:
  /v1/payAt/adviseTransaction:
    post:
      operationId: PayAtService_adviseTransaction
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPayAtTransactionAdviceResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - PayAtService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelPayAtTransactionAdviceRequest'
        required: true
      summary: Pay at service advise transaction
      x-summary-source: derived
  /v1/payAt/authorize:
    post:
      operationId: PayAtService_authorize
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPayAtAuthorizationResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - PayAtService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelPayAtAuthorizationRequest'
        required: true
      summary: Pay at service authorize
      x-summary-source: derived
  /v1/payAt/echoTest:
    post:
      operationId: PayAtService_echoTest
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPayAtEchoTestResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - PayAtService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelPayAtEchoTestRequest'
        required: true
      summary: Pay at service echo test
      x-summary-source: derived
  /v1/payAt/enquire:
    post:
      operationId: PayAtService_enquiry
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPayAtEnquiryResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - PayAtService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelPayAtEnquiryRequest'
        required: true
      summary: Pay at service enquiry
      x-summary-source: derived
  /v1/payAt/reverseAuthorization:
    post:
      operationId: PayAtService_reverseAuthorization
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPayAtReverseAuthorizationResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - PayAtService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelPayAtReverseAuthorizationRequest'
        required: true
      summary: Pay at service reverse authorization
      x-summary-source: derived
components:
  schemas:
    modelPayAtEchoTestResponse:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        echoData:
          type: string
        responseCode:
          type: string
        responseText:
          type: string
    modelPayAtEchoTestRequest:
      type: object
      properties:
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        messageID:
          type: string
        transmissionDateTime:
          type: string
        echoData:
          type: string
    modelPayAtAuthorizationRequest:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        amount:
          type: integer
          format: int32
        networkTransactionID:
          type: string
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
    modelPayAtCustomerData:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
    modelPayAtSecurityData:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/modelPayAtLoginData'
    modelPayAtEnquiryRequest:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        amount:
          type: integer
          format: int32
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
    modelPayAtReverseAuthorizationResponse:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
        networkTransactionID:
          type: string
        responseCode:
          type: string
        responseText:
          type: string
        issuerTransactionID:
          type: string
        repeatIndicator:
          type: boolean
        customerData:
          $ref: '#/components/schemas/modelPayAtCustomerData'
    modelPayAtNetworkData:
      type: object
      properties:
        networkId:
          type: integer
          format: int32
        networkName:
          type: string
    modelPayAtEnquiryResponse:
      type: object
      properties:
        amount:
          type: integer
          format: int32
        dueDate:
          type: string
        exactAmount:
          type: boolean
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
        customerData:
          $ref: '#/components/schemas/modelPayAtCustomerData'
        responseText:
          type: string
        responseCode:
          type: string
    modelPayAtTransactionAdviceResponse:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        tenderType:
          type: string
        repeatIndicator:
          type: boolean
        amount:
          type: integer
          format: int32
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
        networkTransactionID:
          type: string
        issuerTransactionID:
          type: string
        responseCode:
          type: string
        responseText:
          type: string
    modelPayAtLoginData:
      type: object
      properties:
        loginID:
          type: string
        password:
          type: string
    modelPayAtReverseAuthorizationRequest:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        amount:
          type: integer
          format: int32
        networkTransactionID:
          type: string
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
        issuerTransactionID:
          type: string
        repeatIndicator:
          type: boolean
    modelPayAtTransactionAdviceRequest:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        amount:
          type: integer
          format: int32
        tenderType:
          type: string
        repeatIndicator:
          type: boolean
        networkTransactionID:
          type: string
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
        issuerTransactionID:
          type: string
    modelPayAtAuthorizationResponse:
      type: object
      properties:
        messageID:
          type: string
        transmissionDateTime:
          type: string
        securityData:
          $ref: '#/components/schemas/modelPayAtSecurityData'
        accountNumber:
          type: string
        networkData:
          $ref: '#/components/schemas/modelPayAtNetworkData'
        networkTransactionID:
          type: string
        responseCode:
          type: string
        responseText:
          type: string
        issuerTransactionID:
          type: string
        customerData:
          $ref: '#/components/schemas/modelPayAtCustomerData'
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
