openapi: 3.2.0
info:
  title: Layup endpoints Terminal Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: TerminalService
paths:
  /v1/terminals:
    get:
      operationId: TerminalService_get
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelTerminalsResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - TerminalService
      summary: Terminal service get
      x-summary-source: derived
    post:
      operationId: TerminalService_create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelTerminalResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - TerminalService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelTerminalCreateRequest'
        required: true
      summary: Terminal service create
      x-summary-source: derived
  /v1/terminals/{id}:
    put:
      operationId: TerminalService_update
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelTerminalResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - TerminalService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelTerminalServiceupdateBody'
        required: true
      summary: Terminal service update
      x-summary-source: derived
  /v1/terminals/{serial}:
    get:
      operationId: TerminalService_getBySerial
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelTerminalResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: serial
        in: path
        required: true
        schema:
          type: string
      tags:
      - TerminalService
      summary: Terminal service get by serial
      x-summary-source: derived
components:
  schemas:
    modelTerminalResponse:
      type: object
      properties:
        id:
          type: string
        provider:
          type: string
        serial:
          type: string
        model:
          type: string
        active:
          type: boolean
        billable:
          type: boolean
        merchantId:
          type: string
        location:
          type: string
        defaultOrderName:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    modelTerminalsResponse:
      type: object
      properties:
        terminals:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelTerminalResponse'
    modelTerminalServiceupdateBody:
      type: object
      properties:
        productId:
          type: string
        active:
          type: boolean
        billable:
          type: boolean
        merchantId:
          type: string
        location:
          type: string
        userId:
          type: string
    modelTerminalCreateRequest:
      type: object
      properties:
        provider:
          type: string
        serial:
          type: string
        model:
          type: string
        productId:
          type: string
        active:
          type: boolean
        billable:
          type: boolean
        merchantId:
          type: string
        location:
          type: string
        userId:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
