openapi: 3.2.0
info:
  title: Layup endpoints Payment Provider Settlement Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: PaymentProviderSettlementService
paths:
  /v1/paymentProviderSettlements:
    post:
      operationId: PaymentProviderSettlementService_create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPaymentProviderSettlementsResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - PaymentProviderSettlementService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelPaymentProviderSettlementsRequest'
        required: true
      summary: Payment provider settlement service create
      x-summary-source: derived
  /v1/paymentProviderSettlements/link-batch:
    put:
      operationId: PaymentProviderSettlementService_linkBatch
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: ids
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: bankTransactionBatchId
        in: query
        required: true
        schema:
          type: string
      tags:
      - PaymentProviderSettlementService
      summary: Payment provider settlement service link batch
      x-summary-source: derived
  /v1/paymentProviderSettlements/{id}/linkPayment/{paymentId}:
    put:
      operationId: PaymentProviderSettlementService_linkPayment
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPaymentProviderSettlementResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: paymentId
        in: path
        required: true
        schema:
          type: string
      tags:
      - PaymentProviderSettlementService
      summary: Payment provider settlement service link payment
      x-summary-source: derived
components:
  schemas:
    modelPaymentProviderSettlementsResponse:
      type: object
      properties:
        settlements:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelPaymentProviderSettlementResponse'
    modelPaymentProviderSettlement:
      type: object
      properties:
        amountInCents:
          type: integer
          format: int32
        reference:
          type: string
        paymentProvider:
          type: string
        paymentProviderPaymentId:
          type: string
        transactionDate:
          type: string
        paymentReference:
          type: string
        fileStorageReference:
          type: string
        paymentMethod:
          type: string
        feeInCents:
          type: integer
          format: int32
    modelPaymentProviderSettlementsRequest:
      type: object
      properties:
        paymentProviderSettlements:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelPaymentProviderSettlement'
    modelPaymentProviderSettlementResponse:
      type: object
      properties:
        amountInCents:
          type: integer
          format: int32
        reference:
          type: string
        paymentProvider:
          type: string
        paymentProviderPaymentId:
          type: string
        transactionDate:
          type: string
        paymentReference:
          type: string
        fileStorageReference:
          type: string
        paymentMethod:
          type: string
        feeInCents:
          type: integer
          format: int32
        _id:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
