openapi: 3.2.0
info:
  title: Layup endpoints User Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: UserService
paths:
  /v1/users:
    get:
      operationId: UserService_GetMany
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelUserResponseMany'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: orderId
        in: query
        required: false
        schema:
          type: string
      tags:
      - UserService
      summary: User service get many
      x-summary-source: derived
    post:
      summary: Description
      operationId: UserService_Create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelUserResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      - name: avs
        in: query
        required: false
        schema:
          type: string
      - name: isRealtimeVerification
        in: query
        required: false
        schema:
          type: boolean
      tags:
      - UserService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelUserRequest'
        required: true
  /v1/users/{_id}:
    get:
      operationId: UserService_Get
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelUserResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserService
      summary: User service get
      x-summary-source: derived
    delete:
      summary: Description
      operationId: UserService_Del
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelUserResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: path
        required: true
        schema:
          type: string
      tags:
      - UserService
    put:
      operationId: UserService_Update
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelUserResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: path
        required: true
        schema:
          type: string
      - name: avs
        in: query
        required: false
        schema:
          type: string
      - name: isRealtimeVerification
        in: query
        required: false
        schema:
          type: boolean
      tags:
      - UserService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelUserRequest'
        required: true
      summary: User service update
      x-summary-source: derived
components:
  schemas:
    modelBankInfo:
      type: object
      properties:
        bankName:
          $ref: '#/components/schemas/modelBankValidation'
        account:
          $ref: '#/components/schemas/modelBankValidation'
        accountType:
          $ref: '#/components/schemas/modelBankValidation'
        branchCode:
          $ref: '#/components/schemas/modelBankValidation'
        idNumber:
          $ref: '#/components/schemas/modelBankValidation'
        verified:
          type: boolean
        clientName:
          $ref: '#/components/schemas/modelBankValidation'
        cellNumber:
          $ref: '#/components/schemas/modelBankValidation'
        initials:
          $ref: '#/components/schemas/modelBankValidation'
        email:
          $ref: '#/components/schemas/modelBankValidation'
        validationResponseErrors:
          type: array
          items:
            type: string
    modelBillingAddress:
      type: object
      properties:
        country:
          type: string
        province:
          type: string
        streetAddress:
          type: string
        city:
          type: string
        postalCode:
          type: string
    modelMerchants:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
    modelBankValidation:
      type: object
      properties:
        verified:
          type: boolean
        value:
          type: string
    modelMerchantOnboarding:
      type: object
      properties:
        name:
          type: string
        physicalAddress:
          $ref: '#/components/schemas/modelBillingAddress'
    modelUserResponseMany:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelUserResponse'
    modelUserResponse:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        idNumber:
          type: string
        address:
          type: string
        postalCode:
          type: string
        city:
          type: string
        province:
          type: string
        country:
          type: string
        role:
          type: string
          enum:
          - CLIENT
          - MERCHANT
          - ADMIN
          default: CLIENT
        active:
          type: boolean
        merchantId:
          type: string
        cellNumber:
          type: string
        dateOfBirth:
          type: string
        name:
          type: string
        verified:
          type: boolean
        timestamp:
          type: number
          format: double
        hasPassword:
          type: boolean
        verifiedEmail:
          type: boolean
        verifiedMobile:
          type: boolean
        merchantRole:
          type: string
        bankDetails:
          $ref: '#/components/schemas/modelBankInfo'
        merchantOnboarding:
          $ref: '#/components/schemas/modelMerchantOnboarding'
        bankValidationPendingReference:
          type: string
        oneTimePass:
          type: string
        passportState:
          type: string
        passportNumber:
          type: string
        profileImage:
          type: string
        merchantIds:
          type: array
          items:
            type: string
        merchants:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelMerchants'
        isMerchantOwner:
          type: boolean
        twoFactorAuthenticationRequired:
          type: boolean
    modelUserRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        idNumber:
          type: string
        address:
          type: string
        postalCode:
          type: string
        city:
          type: string
        province:
          type: string
        country:
          type: string
        role:
          type: string
          enum:
          - CLIENT
          - MERCHANT
          - ADMIN
          default: CLIENT
        password:
          type: string
        active:
          type: boolean
        name:
          type: string
        dateOfBirth:
          type: string
        cellNumber:
          type: string
          pattern: ^\+27\d{9}$
        redirectTo:
          type: string
        apikey:
          type: string
        shouldWelcome:
          type: boolean
        merchantCreatePlan:
          type: boolean
        merchantId:
          type: string
        merchantRole:
          type: string
        bankDetails:
          $ref: '#/components/schemas/modelBankInfo'
        merchantOnboarding:
          $ref: '#/components/schemas/modelMerchantOnboarding'
        bankValidationPendingReference:
          type: string
        passportState:
          type: string
        passportNumber:
          type: string
        profileImage:
          type: string
        merchantIds:
          type: array
          items:
            type: string
        isMerchantOwner:
          type: boolean
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
