openapi: 3.2.0
info:
  title: Layup endpoints Debi Check Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: DebiCheckService
paths:
  /v1/debicheck:
    post:
      operationId: DebiCheckService_CreateLegacy
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebiCheckMandateResponseLegacy'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      tags:
      - DebiCheckService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelDebiCheckRequestLegacy'
        required: true
      summary: Debi check service create legacy
      x-summary-source: derived
  /v1/debicheck/collection:
    get:
      operationId: DebiCheckService_GetManyCollection
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebiCheckCollectionResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: due
        in: query
        required: false
        schema:
          type: string
      tags:
      - DebiCheckService
      summary: Debi check service get many collection
      x-summary-source: derived
    post:
      operationId: DebiCheckService_CreateCollection
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebiCheckCollection'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      tags:
      - DebiCheckService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelDebiCheckCollectionRequest'
        required: true
      summary: Debi check service create collection
      x-summary-source: derived
  /v1/debicheck/list/{_id}:
    get:
      operationId: DebiCheckService_GetMandateList
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebiCheckMandateListResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: path
        required: true
        schema:
          type: string
      tags:
      - DebiCheckService
      summary: Debi check service get mandate list
      x-summary-source: derived
  /v1/debicheck/{_id}:
    get:
      operationId: DebiCheckService_GetMandate
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebiCheckMandateResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: path
        required: true
        schema:
          type: string
      tags:
      - DebiCheckService
      summary: Debi check service get mandate
      x-summary-source: derived
  /v2/debi-check:
    post:
      operationId: DebiCheckService_Create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelDebiCheckMandateResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      tags:
      - DebiCheckService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelDebiCheckRequest'
        required: true
      summary: Debi check service create
      x-summary-source: derived
components:
  schemas:
    modelDebiCheckRequestLegacy:
      type: object
      properties:
        name:
          type: string
          title: Name and Surname
        accountType:
          type: string
        accountNumber:
          type: string
        branchCode:
          type: string
          title: 6-digit branch code
        contact:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelDebiCheckContactLegacy'
        identificationType:
          type: string
        identification:
          type: string
        paymentPlanId:
          type: string
        simulation:
          type: boolean
    modelDebiCheckContactLegacy:
      type: object
      properties:
        medium:
          type: string
        value:
          type: string
    modelDebiCheckCollectionResponse:
      type: object
      properties:
        collections:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelDebiCheckCollection'
    modelDebiCheckContact:
      type: object
      properties:
        medium:
          $ref: '#/components/schemas/modelDebiCheckMediumEnum'
        value:
          type: string
    modelDebiCheckAccountTypeEnum:
      type: integer
      format: int32
      example: Current
      enum:
      - 0
      - 1
      - 2
      default: 0
      x-enum-varnames:
      - Current
      - Savings
      - Transmission
    modelDebiCheckMandateListResponse:
      type: object
      properties:
        status:
          type: string
        debicheckFailedReasons:
          type: array
          items:
            type: string
    modelDebiCheckCollectionRequest:
      type: object
      properties:
        due:
          type: string
    modelDebiCheckCollection:
      type: object
      properties:
        raw:
          type: string
    modelDebiCheckMandateContactLegacy:
      type: object
      properties:
        medium:
          type: integer
          format: int32
        value:
          type: string
    modelDebiCheckMediumEnum:
      type: integer
      format: int32
      example: PhoneNumber
      enum:
      - 0
      - 1
      default: 0
      x-enum-descriptions:
      - Phone Number (in international format, e.g., +1 415 555 2671)
      - Email address
      x-enum-varnames:
      - PhoneNumber
      - EmailAddress
    modelDebiCheckMandateResponseLegacy:
      type: object
      properties:
        _id:
          type: string
        customer:
          $ref: '#/components/schemas/modelDebiCheckMandateCustomerLegacy'
        createdAt:
          type: string
        simulation:
          type: boolean
    modelDebiCheckMandateContact:
      type: object
      properties:
        medium:
          $ref: '#/components/schemas/modelDebiCheckMediumEnum'
        value:
          type: string
    modelDebiCheckIdentificationTypeEnum:
      type: integer
      format: int32
      example: IdentityDocument
      enum:
      - 0
      - 1
      - 2
      default: 0
      x-enum-varnames:
      - IdentityDocument
      - Passport
      - TemporaryResidence
    modelDebiCheckMandateCustomerLegacy:
      type: object
      properties:
        name:
          type: string
        identification:
          type: string
        identificationType:
          type: string
        accountType:
          type: string
        accountNumber:
          type: string
        branchCode:
          type: string
        contact:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelDebiCheckMandateContactLegacy'
        simulated:
          type: boolean
    modelDebiCheckRequest:
      type: object
      properties:
        name:
          type: string
          title: Name and Surname
        accountType:
          $ref: '#/components/schemas/modelDebiCheckAccountTypeEnum'
        accountNumber:
          type: string
        branchCode:
          type: string
          title: 6-digit branch code
        contact:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelDebiCheckContact'
        identificationType:
          $ref: '#/components/schemas/modelDebiCheckIdentificationTypeEnum'
        identification:
          type: string
        paymentPlanId:
          type: string
        simulation:
          type: boolean
    modelDebiCheckMandateCustomer:
      type: object
      properties:
        name:
          type: string
        identification:
          type: string
        identificationType:
          type: string
        accountType:
          type: string
        accountNumber:
          type: string
        branchCode:
          type: string
        contact:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelDebiCheckMandateContact'
        simulated:
          type: boolean
    modelDebiCheckMandateResponse:
      type: object
      properties:
        _id:
          type: string
        customer:
          $ref: '#/components/schemas/modelDebiCheckMandateCustomer'
        createdAt:
          type: string
        simulation:
          type: boolean
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
