openapi: 3.2.0
info:
  title: Layup endpoints International Msisdn Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: InternationalMsisdnService
paths:
  /v1/international-msisdns:
    get:
      operationId: InternationalMsisdnService_GetMany
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInternationalMsisdnResponseMany'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: countryCode
        in: query
        required: false
        schema:
          type: string
      - name: msisdn
        in: query
        required: false
        schema:
          type: string
      tags:
      - InternationalMsisdnService
      summary: International msisdn service get many
      x-summary-source: derived
    post:
      operationId: InternationalMsisdnService_Update
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInternationalMsisdnResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      tags:
      - InternationalMsisdnService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelInternationalMsisdnRequest'
        required: true
      summary: International msisdn service update
      x-summary-source: derived
  /v1/international-msisdns/{_id}:
    get:
      operationId: InternationalMsisdnService_Get
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInternationalMsisdnResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: path
        required: true
        schema:
          type: string
      tags:
      - InternationalMsisdnService
      summary: International msisdn service get
      x-summary-source: derived
    delete:
      operationId: InternationalMsisdnService_Del
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelInternationalMsisdnResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: path
        required: true
        schema:
          type: string
      tags:
      - InternationalMsisdnService
      summary: International msisdn service del
      x-summary-source: derived
components:
  schemas:
    modelInternationalMsisdnRequest:
      type: object
      properties:
        msisdn:
          type: string
        countryCode:
          type: string
    modelInternationalMsisdnResponse:
      type: object
      properties:
        msisdn:
          type: string
        countryCode:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    modelInternationalMsisdnResponseMany:
      type: object
      properties:
        internationalMsisdns:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelInternationalMsisdnResponse'
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
