openapi: 3.2.0
info:
  title: Layup endpoints Payment Service V2 API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: PaymentServiceV2
paths:
  /v2/payments:
    post:
      operationId: PaymentServiceV2_Create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPaymentRedirectResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: _id
        in: query
        required: false
        schema:
          type: string
      tags:
      - PaymentServiceV2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelPaymentRequestV2'
        required: true
      summary: Payment service V2 create
      x-summary-source: derived
  /v2/payments-report:
    get:
      operationId: PaymentServiceV2_GetReport
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelPaymentReportResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: merchantId
        in: query
        required: false
        schema:
          type: string
      - name: skip
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: paid
        in: query
        required: false
        schema:
          type: boolean
      - name: orderId
        in: query
        required: false
        schema:
          type: string
      - name: paymentPlanId
        in: query
        required: false
        schema:
          type: string
      - name: userId
        in: query
        required: false
        schema:
          type: string
      - name: fromDate
        in: query
        required: false
        schema:
          type: string
      - name: toDate
        in: query
        required: false
        schema:
          type: string
      - name: method
        in: query
        required: false
        schema:
          type: string
      - name: type
        in: query
        required: false
        schema:
          type: string
      - name: search
        in: query
        required: false
        schema:
          type: string
      - name: fromDatePayments
        in: query
        required: false
        schema:
          type: string
      - name: toDatePayments
        in: query
        required: false
        schema:
          type: string
      - name: settled
        in: query
        required: false
        schema:
          type: string
      - name: sort
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: failed
        in: query
        required: false
        schema:
          type: boolean
      - name: provider
        in: query
        required: false
        schema:
          type: string
      - name: destinationId
        in: query
        required: false
        schema:
          type: string
      - name: destinationType
        in: query
        required: false
        schema:
          type: string
      tags:
      - PaymentServiceV2
      summary: Payment service V2 get report
      x-summary-source: derived
components:
  schemas:
    modelPaymentReportResponse:
      type: object
      properties:
        payments:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelReportPayment'
        export:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelReportExport'
    modelFee:
      type: object
      properties:
        id:
          type: string
        productName:
          type: string
        amountExcludingVAT:
          type: number
          format: double
        amountVAT:
          type: number
          format: double
        amountTotal:
          type: number
          format: double
        merchantId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        settlementId:
          type: string
        paymentId:
          type: string
    modelPaymentRequestV2:
      type: object
      properties:
        destinationId:
          type: string
        amount:
          type: integer
          format: int32
        redirectUrl:
          type: string
        paymentMethod:
          type: string
        paymentProvider:
          type: string
        destinationType:
          type: string
          title: paymentPlan | invoice
        connectorData:
          $ref: '#/components/schemas/modelConnectorDataV2'
        save:
          type: boolean
    modelConnectorDataV2:
      type: object
      properties:
        bankTransactionId:
          type: string
    modelFeePerProduct:
      type: object
      properties:
        quantity:
          type: number
          format: double
        amountTotal:
          type: number
          format: double
        amountExcludingVAT:
          type: number
          format: double
        amountVAT:
          type: number
          format: double
        product:
          $ref: '#/components/schemas/modelProduct'
    modelReportExport:
      type: object
      properties:
        client:
          type: string
        amount:
          type: number
          format: double
        createdAt:
          type: string
        verifiedAt:
          type: string
        due:
          type: string
        fee:
          type: number
          format: double
        orderName:
          type: string
        orderReference:
          type: string
        paymentStatus:
          type: string
        paymentType:
          type: string
        settlementBatch:
          type: string
        state:
          type: string
        updatedAt:
          type: string
        datePaid:
          type: string
        dateSettled:
          type: string
    modelReportPayment:
      type: object
      properties:
        id:
          type: string
        amount:
          type: number
          format: double
        client:
          type: string
        createdAt:
          type: string
        datePaid:
          type: string
        due:
          type: string
        fee:
          type: number
          format: double
        fees:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelFee'
        feesPerProduct:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelFeePerProduct'
        locked:
          type: boolean
        orderName:
          type: string
        orderReference:
          type: string
        paymentMethod:
          type: string
        paymentStatus:
          type: string
        paymentType:
          type: string
        settlementBatch:
          type: string
        state:
          type: string
        updatedAt:
          type: string
        verifiedAt:
          type: string
        dateSettled:
          type: string
    modelNameAndValue:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    modelPaymentRedirectResponse:
      type: object
      properties:
        url:
          type: string
        parameters:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelNameAndValue'
        method:
          type: string
        _id:
          type: string
        checkoutId:
          type: string
    modelProduct:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        displayName:
          type: string
        feeType:
          type: string
        method:
          type: string
        billingType:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
