openapi: 3.2.0
info:
  title: Layup endpoints Absa Debi Check Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: AbsaDebiCheckService
paths:
  /v1/absa/debicheck/output:
    post:
      operationId: AbsaDebiCheckService_output
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelAbsaDebiCheckResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - AbsaDebiCheckService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelAbsaDebiCheckOutputRequest'
        required: true
      summary: Absa debi check service output
      x-summary-source: derived
  /v1/absa/debicheck/reply:
    post:
      operationId: AbsaDebiCheckService_reply
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelAbsaDebiCheckResponse'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      tags:
      - AbsaDebiCheckService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/modelAbsaDebiCheckReplyRequest'
        required: true
      summary: Absa debi check service reply
      x-summary-source: derived
components:
  schemas:
    modelAbsaDebiCheckResponse:
      type: object
    modelAbsaDebiCheckOutputTransaction:
      type: object
      properties:
        paymentId:
          type: string
        accepted:
          type: boolean
        contractReference:
          type: string
        mandateReference:
          type: string
        sequenceType:
          type: string
        amountInCents:
          type: integer
          format: int32
        effectiveDate:
          type: string
        originalEndToEndTransactionIdentifier:
          type: string
        error:
          type: string
    modelRejectedReasons:
      type: object
      properties:
        contractReference:
          type: string
        reason:
          type: string
    modelAbsaDebiCheckOutputRequest:
      type: object
      properties:
        transmissionDate:
          type: string
        fileStoragePath:
          type: string
        transactions:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelAbsaDebiCheckOutputTransaction'
    modelAbsaDebiCheckReplyRequest:
      type: object
      properties:
        transmissionNumber:
          type: string
        transmissionDate:
          type: string
        transmissionStatus:
          type: string
        fileStoragePath:
          type: string
        rejectedReasons:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelRejectedReasons'
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
