openapi: 3.2.0
info:
  title: Layup endpoints Integration Service API
  version: 1.4.16
  description: Welcome to The Layup Swagger page.
servers:
- url: http://localhost:3000
- url: https://localhost:3000
- url: wss://localhost:3000
security:
- apiKey:
  - read
  - write
tags:
- name: IntegrationService
paths:
  /v1/integrations/cue/user/{cellNumber}/orders:
    get:
      operationId: IntegrationService_GetCueOrders
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/modelCueOrderResponseMany'
        '204':
          description: Successfully processed the request, no content.
        '403':
          description: Returned when the user does not have permission to access the resource.
        '404':
          description: Returned when the resource does not exist.
      parameters:
      - name: cellNumber
        in: path
        required: true
        schema:
          type: string
      tags:
      - IntegrationService
      summary: Integration service get cue orders
      x-summary-source: derived
components:
  schemas:
    modelCueOrder:
      type: object
      properties:
        reference:
          type: string
        endDateMax:
          type: string
        dueDate:
          type: string
        balance:
          type: integer
          format: int32
        cancellationFee:
          type: integer
          format: int32
    modelCueOrderResponseMany:
      type: object
      properties:
        orders:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/modelCueOrder'
  securitySchemes:
    apiKey:
      type: apiKey
      name: apikey
      in: header
